### ISSUE TITLE
How does the plugin get access to the endpoint

### ISSUE THREAD

**Issue by domien96** [nucleon/wintertodt-scouter#1]
I tried to manually make a GET request via Postman, but my access is forbidden by Cloudflare. So I was wondering how the plugin manages to gain access.

**Comment by nucleon** [comment]
the plugin manages to gain access because the server is tailored and hardened to accept requests from a specific range of acceptable runelite client versions that are present in the user agent of the get request, if you want to see a sample of the returned data I can show it to you here.

**Comment by nucleon** [comment]
the plugin doesn't do anything special to gain access, but the server decides whether or not the GET request is legit

**Comment by domien96** [comment]
I tried with the user-agent `Runelite Wiki Scraper/1.0 (+abex@runelite.net)`, but that didn't work so probably it is not in the list.
I was wondering what cloudflare is precisely protecting here. Can't every machine make requests with a custom user agent? Of course the user agent being one within the list.

**Comment by nucleon** [comment]
requests cost money, cloudflare is limiting the number of requests and monitoring the authenticity of the requests to save me money since the server isn’t free
