### ISSUE TITLE
Its not working and I'm not sure why?

### ISSUE THREAD

**Issue by raysdigitalfootprint** [nucleon/wintertodt-scouter#2]
does not display any worlds except for the one I'm currently on. My clan mates have confirmed its not working for them as well. it might be because W307 the USA wintertodt world has been down for some time?

**Comment by nucleon** [comment]
Hello, this plugin is crowdsourced meaning other runelite users must have the plugin loaded and be active in that world inside the wintertodt game area. When this happens, upstream data will populate the server and your client will have an updated record.

Now, it sounds like the plugin is less active than previously. My only advice is to spread it by word of mouth inside the game servers so many more people can upload data.

**Comment by raysdigitalfootprint** [comment]
I understand how it works and what you're saying. I've used it for 7m XP over the last 2 weeks. Since US W307 Wintertodt world went down and is still down, now the plugin is broken. I was in WT when it happened and observed the plugin breaking.

This is not a crowed sourcing issue. Previously if there was no one in a world to source the WT % the plugin would show a CROSS through the signal icon next to the world number to say there's no info to display - I have seen it may times before sometimes 2 of the 4 worlds would not have info to display so 2 worlds would have a cross and the others have WT%

This is not the issue that I am reporting. Since the US W307 went down the plugin does not display any worlds in the list except the one you're on. Do you understand? It used to show 4 worlds at all times even if there was no WT %, now there is no worlds on the list unless you're on a WT world yourself.

Also, this plugin is actually pretty popular. I would hardly ever see a WT world with no %.

**Comment by nucleon** [comment]
I'll look into it.

**Comment by nucleon** [comment]
I deleted w307 from the server, is it working now?

**Comment by raysdigitalfootprint** [comment]
its working!! thanks so much!!
