### ISSUE TITLE
Doesnt work anymore

### ISSUE THREAD

**Issue by Fathlete** [nucleon/wintertodt-scouter#6]
Hey, used this earlier this week and it worked fine - aside from double clicking to hop being buggy.

Now it doesnt work at all. HP/worlds stuck like this (see pic below). Tried playing a game, tried restarting RL, uninstalling and reinstalling the plugin. Nada. 

![bild](https://github.com/nucleon/wintertodt-scouter/assets/40322649/3a5aae84-a549-4c85-86e9-4124c2a801dc)

**Comment by undercoverworm** [comment]
I am having the same issue

**Comment by nucleon** [comment]
I looked into it, scheduled actions aren't triggering anymore. I'll dig around.

**Comment by nucleon** [comment]
WT was patched recently and the widget was reworked,
adding the pull request with the fix now

**Comment by miumarvin** [comment]
Hi Nucleon, can I double check that the fix has gone live please?
