### ISSUE TITLE
Scouter Not working since wintertodt update this week

### ISSUE THREAD

**Issue by EightZeroNine** [nucleon/wintertodt-scouter#7]
Plugin appears to not be working for me still - I tried to visit the website that the plugin uses as a repository and it said I have been blocked, maybe because I tried to access it from a browser - does that mean the plugin won't work for me anymore?

**Comment by nucleon** [comment]
It will work again when the runelite maintainers with write access decide to merge the pull request to fix it

**Comment by EightZeroNine** [comment]
Awesome, thanks so much for the quick response and making/updating this plugin!
