### ISSUE TITLE
Add-on doesnt work anymore

### ISSUE THREAD

**Issue by Celesticlady** [nucleon/wintertodt-scouter#8]
Title says it all

**Comment by Fathlete** [comment]
To add onto this, the developers pushed the merger thing you mentioned but now none of the worlds show up in the list.

![bild](https://github.com/nucleon/wintertodt-scouter/assets/40322649/cb92a24a-f7b8-4653-ac6c-620bcabcf41b)

**Comment by nucleon** [comment]
yea I broke it should be ok now
