### ISSUE TITLE
Plugin broke for me

### ISSUE THREAD

**Issue by Onlyx3** [nucleon/wintertodt-scouter#9]
Heya, 

Cloudflare blocked me from accessing your WT Scouter. The Ray ID is "81bb4bc53b863677". I hope we can resolve this somehow.

**Comment by nucleon** [comment]
It’s not broken, I used it today. Are you just trying to visit the website in your browser? This is blocked for everyone.

**Comment by Onlyx3** [comment]
mb, ingame it now works, it wasnt working ingame today and as i tried to visit the website i saw that i was cloudflare blocked and made assumptions myself.
